### ISSUE TITLE
The download archive for this library needs fixing

### ISSUE THREAD

**Issue by asampal** [josephtaylor/sketch-mapper#11]
When you try to update this library from within Processing 3.0.2, I see that I have what looks to be version 3.0.1 and it's shown as outdated with a version 4.0.0 available. When I try to update, the update fails. Looking at `library.properties`, I think the version might be incorrect for the current version available for download.

**Comment by josephtaylor** [comment]
thanks for letting me know about this. updated the archive on the site to have the right properties file. just ran an update in processing 3 from 3.0.1 to 4.0.0 and it seems to be working.
