### ISSUE TITLE
Error when applied on Multiple Surfaces

### ISSUE THREAD

**Issue by luukschipperheyn** [josephtaylor/sketch-mapper#14]
Hey,

I'm super happy that your library exists! However, it only seems to work with a single surface. Once I add another surface (or even use your saved template for the 3 surface cube form) on my machine [Macbook Pro Late 2011, Processing 3.2.4] I get an instant crash which shows this error message:

```
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
Projection layout loaded from test_layout.xml. 3 surfaces were loaded!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001264af068, pid=3596, tid=0x0000000000012007
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [AppleIntelHD3000GraphicsGLDriver+0x271068]  gldBlitFramebufferData+0x3fb
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/luukschipperheyn/hs_err_pid3596.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.
```

I have no idea what might cause this. I have already enabled core dumping as the error message encourages, but this didnt change anything. I get the feeling it has to do with the fact that ControlP5's latest library is 2.2.6 and that your repository is supposedly working on 2.2.5? But this seems like a strange reason.

Any help would be greatly appreciated!

Cheers,
Luuk

**Comment by josephtaylor** [comment]
What version of OSX are you running? Could it possible be related to this issue with processing itself?
https://github.com/processing/processing/issues/4104

Here's Processing's page about Supported Platforms:
https://github.com/processing/processing/wiki/Supported-Platforms#mac-os-x


If your machine doesn't match the setup in that issue I can try to reproduce it on my mac. Just let me know.
