### ISSUE TITLE
NullPointerException in SketchMapperTest example

### ISSUE THREAD

**Issue by josephtaylor** [josephtaylor/sketch-mapper#17]
## Steps to reproduce
1. open the `SketchMapperTest` example.
2. click on run.

Appears to work if you add a second surface and sketches for both of them.

Processing Version: 3.3.5
Operating System: Xubuntu 16.04
Kernel Version:  4.10.12-041012-generic

**Comment by jmej** [comment]
I just experienced this bug in windows as well - but the other example seems to be running fine. Not sure what you mean by adding a second service?

**Comment by josephtaylor** [comment]
Ah i'm sorry I meant to say "surface" there, I'll update it

**Comment by jmej** [comment]
Ah that makes sense! Yeah it works for me - I have to not only add a second quad but make sure both have sketches assigned to them.
