### ISSUE TITLE
Super slow in Processing 3

### ISSUE THREAD

**Issue by josephtaylor** [josephtaylor/sketch-mapper#8]
There seems to be a memory leak or something going on. As soon as you interact with the mapping UI everything gets sluggish quickly and the memory usage spikes up.

Need to do some profiling and see what's going on.

**Comment by josephtaylor** [comment]
Is anyone else experiencing this ? I think it may just be my machine, because the processing 2 version is running slow as well.

**Comment by jmej** [comment]
Things are running kinda slow here too - but I don't have any baseline for comparison.

**Comment by josephtaylor** [comment]
I think i had two or three surfaces with a pretty simple sketch on them and was seeing it lag visibly, so I guess the frame rate dropped. That might be a good metric to gather? not sure.

Maybe dump out some frameRate info?
https://processing.org/reference/frameRate.html

```
println(frameRate);
```
inside `draw()` somewhere.

**Comment by jmej** [comment]
Gotcha. And you're interested in some metrics comparing processing 2 to 3? Or just general performance?

**Comment by josephtaylor** [comment]
I guess both? honestly I haven't played with this in a long time but I remember with Processing 2, everything seemed to run smoothly. Then, when I created this issue in 2015 I had tried it against processing 3 and found that it was slow to the point of being basically unusable.

**Comment by josephtaylor** [comment]
Just ran the example in Processing 3.4 and I'm not really seeing slowness anymore
